name: ping supabase

on:
    workflow_dispatch:
    schedule:
        - cron: 0 4 1,6,11,16,21,26 * *

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo content
              uses: actions/checkout@v4

            - name: setup python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10.7"

            - name: install python packages
              run: |
                  python3 -m pip install --upgrade pip
                  pip install -r backend/scripts/requirements.txt

            - name: execute ping_supabase.py
              env:
                  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
                  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
              run: python3 backend/scripts/ping_supabase.py
